### ISSUE TITLE
command should runs as a normal user

### ISSUE THREAD

**Issue by withanage** [withanage/HEIDIEditor#40]
unoconv -f docx -o /path/to/out_folder/doc/new.docx /path/to/input_file.doc

**Comment by nwp90** [comment]
Assuming your webserver runs as `www-data`, I suspect you need to create `~www-data/.config` (on Debian this will be `/var/www/.config`) and make it writable by `www-data`:

> chown www-data ~www-data/.config; chmod 700 ~www-data/.config

-  as libreoffice needs to be able to write config files here (or in one of several other places it tries, but this is its favourite).

**Comment by withanage** [comment]
thanks a lot for the advice  @nwp90

**Comment by mohammedyunus009** [comment]
Try this script too
```

import subprocess
import glob
import threading

files = glob.glob("./res/*")
def threa(file):
    print ( subprocess.call(['soffice', '--invisible','--headless','--convert-to', 'html',file]) )
#     print ( subprocess.call(["unoconv", "-d" ,"document", "--format=html", file]) )

for i in files:
	t1 = threading.Thread(target= threa , args=(i,))
	t1.start()

```
Even this will give the same error , So the base problem with libreoffice is , it cannot open many instances of libreoffice (In short u can not multi thread to convert the documents ) ,
Solution : The callee should ensure there is no instance of libre office open.
As reffered in [Issue](https://github.com/dagwieers/unoconv/issues/359)
